
name : Github Actions File
on: 
  pull_request:
  push:
    branches:
      -master
      -develop
      
      
jobs:
  test:
    name: Running Units Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: action/checkout@v1
    - name: Use Node.js ${{ matrix.node-version}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version}}
    - name: Install
      run: npn install
    - name: Test
      run: npn test
